package fase1;

import control.ControlGlobal;
import entorno.Refugio;
import entorno.ZonaInsegura;
import java.util.*;
import javax.swing.*;

public class VentanaPrincipal extends javax.swing.JFrame {
    private static Refugio refugio;
    public VentanaPrincipal(Refugio refugio) {
        initComponents();
        ComidaUpdater.iniciar(lblComidaDisponible, refugio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPausa = new javax.swing.JButton();
        zonaInsegura4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnVerHumanosZ3 = new javax.swing.JButton();
        btnVerZombisZ3 = new javax.swing.JButton();
        zonaInsegura3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVerZombisZ2 = new javax.swing.JButton();
        btnVerHumanosZ2 = new javax.swing.JButton();
        zonaInsegura2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVerHumanosZ1 = new javax.swing.JButton();
        btnVerZombisZ1 = new javax.swing.JButton();
        zonaInsegura1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVerHumanosZ0 = new javax.swing.JButton();
        btnVerZombisZ0 = new javax.swing.JButton();
        zonaComun = new javax.swing.JPanel();
        btnVerZonaComun = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        zonaComedor = new javax.swing.JPanel();
        btnVerComedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblComidaDisponible = new javax.swing.JLabel();
        zonaDescanso = new javax.swing.JPanel();
        btnVerDescanso = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tunel3_1 = new javax.swing.JPanel();
        tunel3_2 = new javax.swing.JPanel();
        tunel2 = new javax.swing.JPanel();
        tunel1 = new javax.swing.JPanel();
        tunel4_1 = new javax.swing.JPanel();
        tunel4_2 = new javax.swing.JPanel();
        tunel4_3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        botonPausa.setText("Pausar");
        botonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausaActionPerformed(evt);
            }
        });
        getContentPane().add(botonPausa);
        botonPausa.setBounds(920, 560, 70, 30);

        zonaInsegura4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaInsegura4.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaInsegura4.setName(""); // NOI18N
        zonaInsegura4.setPreferredSize(new java.awt.Dimension(230, 230));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zona Insegura 3");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerHumanosZ3.setText("Ver Humanos");
        btnVerHumanosZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHumanosZ3ActionPerformed(evt);
            }
        });

        btnVerZombisZ3.setText("Ver Zombis");
        btnVerZombisZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZombisZ3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaInsegura4Layout = new javax.swing.GroupLayout(zonaInsegura4);
        zonaInsegura4.setLayout(zonaInsegura4Layout);
        zonaInsegura4Layout.setHorizontalGroup(
            zonaInsegura4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura4Layout.createSequentialGroup()
                .addGroup(zonaInsegura4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(zonaInsegura4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(zonaInsegura4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerHumanosZ3)
                            .addComponent(btnVerZombisZ3))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        zonaInsegura4Layout.setVerticalGroup(
            zonaInsegura4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerHumanosZ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerZombisZ3)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        getContentPane().add(zonaInsegura4);
        zonaInsegura4.setBounds(110, 90, 140, 140);

        zonaInsegura3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaInsegura3.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaInsegura3.setName(""); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Zona Insegura 2");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerZombisZ2.setText("Ver Zombis");
        btnVerZombisZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZombisZ2ActionPerformed(evt);
            }
        });

        btnVerHumanosZ2.setText("Ver Humanos");
        btnVerHumanosZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHumanosZ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaInsegura3Layout = new javax.swing.GroupLayout(zonaInsegura3);
        zonaInsegura3.setLayout(zonaInsegura3Layout);
        zonaInsegura3Layout.setHorizontalGroup(
            zonaInsegura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaInsegura3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonaInsegura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerHumanosZ2)
                    .addComponent(btnVerZombisZ2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaInsegura3Layout.setVerticalGroup(
            zonaInsegura3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerHumanosZ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerZombisZ2)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        getContentPane().add(zonaInsegura3);
        zonaInsegura3.setBounds(110, 230, 140, 140);

        zonaInsegura2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaInsegura2.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaInsegura2.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zona Insegura 1");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerHumanosZ1.setText("Ver Humanos");
        btnVerHumanosZ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHumanosZ1ActionPerformed(evt);
            }
        });

        btnVerZombisZ1.setText("Ver Zombis");
        btnVerZombisZ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZombisZ1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaInsegura2Layout = new javax.swing.GroupLayout(zonaInsegura2);
        zonaInsegura2.setLayout(zonaInsegura2Layout);
        zonaInsegura2Layout.setHorizontalGroup(
            zonaInsegura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaInsegura2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonaInsegura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerHumanosZ1)
                    .addComponent(btnVerZombisZ1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaInsegura2Layout.setVerticalGroup(
            zonaInsegura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerHumanosZ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerZombisZ1)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        getContentPane().add(zonaInsegura2);
        zonaInsegura2.setBounds(250, 230, 140, 140);

        zonaInsegura1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaInsegura1.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaInsegura1.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Zona Insegura 0");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerHumanosZ0.setText("Ver Humanos");
        btnVerHumanosZ0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHumanosZ0ActionPerformed(evt);
            }
        });

        btnVerZombisZ0.setText("Ver Zombis");
        btnVerZombisZ0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZombisZ0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaInsegura1Layout = new javax.swing.GroupLayout(zonaInsegura1);
        zonaInsegura1.setLayout(zonaInsegura1Layout);
        zonaInsegura1Layout.setHorizontalGroup(
            zonaInsegura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaInsegura1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonaInsegura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerHumanosZ0)
                    .addComponent(btnVerZombisZ0))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaInsegura1Layout.setVerticalGroup(
            zonaInsegura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaInsegura1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerHumanosZ0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerZombisZ0)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        getContentPane().add(zonaInsegura1);
        zonaInsegura1.setBounds(250, 90, 140, 140);

        zonaComun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaComun.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaComun.setName(""); // NOI18N

        btnVerZonaComun.setText("Ver Humanos");
        btnVerZonaComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZonaComunActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Zona Común");
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout zonaComunLayout = new javax.swing.GroupLayout(zonaComun);
        zonaComun.setLayout(zonaComunLayout);
        zonaComunLayout.setHorizontalGroup(
            zonaComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaComunLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaComunLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnVerZonaComun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaComunLayout.setVerticalGroup(
            zonaComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaComunLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(btnVerZonaComun)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        getContentPane().add(zonaComun);
        zonaComun.setBounds(640, 90, 140, 440);

        zonaComedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaComedor.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaComedor.setName(""); // NOI18N

        btnVerComedor.setText("Ver Humanos");
        btnVerComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComedorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Comedor");
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Comida:");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblComidaDisponible.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        lblComidaDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComidaDisponible.setAlignmentY(0.0F);
        lblComidaDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout zonaComedorLayout = new javax.swing.GroupLayout(zonaComedor);
        zonaComedor.setLayout(zonaComedorLayout);
        zonaComedorLayout.setHorizontalGroup(
            zonaComedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaComedorLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaComedorLayout.createSequentialGroup()
                .addGroup(zonaComedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zonaComedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVerComedor))
                    .addGroup(zonaComedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(zonaComedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblComidaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaComedorLayout.setVerticalGroup(
            zonaComedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaComedorLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerComedor)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComidaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(zonaComedor);
        zonaComedor.setBounds(780, 90, 140, 210);

        zonaDescanso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zonaDescanso.setMinimumSize(new java.awt.Dimension(230, 230));
        zonaDescanso.setName(""); // NOI18N

        btnVerDescanso.setText("Ver Humanos");
        btnVerDescanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDescansoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Zona Descanso");
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout zonaDescansoLayout = new javax.swing.GroupLayout(zonaDescanso);
        zonaDescanso.setLayout(zonaDescansoLayout);
        zonaDescansoLayout.setHorizontalGroup(
            zonaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaDescansoLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(zonaDescansoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVerDescanso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zonaDescansoLayout.setVerticalGroup(
            zonaDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaDescansoLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnVerDescanso)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(zonaDescanso);
        zonaDescanso.setBounds(780, 300, 140, 230);

        tunel3_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel3_1.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel3_1.setName(""); // NOI18N

        javax.swing.GroupLayout tunel3_1Layout = new javax.swing.GroupLayout(tunel3_1);
        tunel3_1.setLayout(tunel3_1Layout);
        tunel3_1Layout.setHorizontalGroup(
            tunel3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tunel3_1Layout.setVerticalGroup(
            tunel3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tunel3_1);
        tunel3_1.setBounds(170, 410, 480, 10);

        tunel3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel3_2.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel3_2.setName(""); // NOI18N

        javax.swing.GroupLayout tunel3_2Layout = new javax.swing.GroupLayout(tunel3_2);
        tunel3_2.setLayout(tunel3_2Layout);
        tunel3_2Layout.setHorizontalGroup(
            tunel3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        tunel3_2Layout.setVerticalGroup(
            tunel3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tunel3_2);
        tunel3_2.setBounds(170, 360, 10, 60);

        tunel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel2.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel2.setName(""); // NOI18N

        javax.swing.GroupLayout tunel2Layout = new javax.swing.GroupLayout(tunel2);
        tunel2.setLayout(tunel2Layout);
        tunel2Layout.setHorizontalGroup(
            tunel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        tunel2Layout.setVerticalGroup(
            tunel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tunel2);
        tunel2.setBounds(380, 300, 270, 10);

        tunel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel1.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel1.setName(""); // NOI18N

        javax.swing.GroupLayout tunel1Layout = new javax.swing.GroupLayout(tunel1);
        tunel1.setLayout(tunel1Layout);
        tunel1Layout.setHorizontalGroup(
            tunel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        tunel1Layout.setVerticalGroup(
            tunel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        getContentPane().add(tunel1);
        tunel1.setBounds(380, 150, 270, 10);

        tunel4_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel4_1.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel4_1.setName(""); // NOI18N

        javax.swing.GroupLayout tunel4_1Layout = new javax.swing.GroupLayout(tunel4_1);
        tunel4_1.setLayout(tunel4_1Layout);
        tunel4_1Layout.setHorizontalGroup(
            tunel4_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        tunel4_1Layout.setVerticalGroup(
            tunel4_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tunel4_1);
        tunel4_1.setBounds(60, 460, 590, 10);

        tunel4_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel4_2.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel4_2.setName(""); // NOI18N

        javax.swing.GroupLayout tunel4_2Layout = new javax.swing.GroupLayout(tunel4_2);
        tunel4_2.setLayout(tunel4_2Layout);
        tunel4_2Layout.setHorizontalGroup(
            tunel4_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        tunel4_2Layout.setVerticalGroup(
            tunel4_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        getContentPane().add(tunel4_2);
        tunel4_2.setBounds(60, 160, 10, 310);

        tunel4_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tunel4_3.setMinimumSize(new java.awt.Dimension(230, 230));
        tunel4_3.setName(""); // NOI18N

        javax.swing.GroupLayout tunel4_3Layout = new javax.swing.GroupLayout(tunel4_3);
        tunel4_3.setLayout(tunel4_3Layout);
        tunel4_3Layout.setHorizontalGroup(
            tunel4_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tunel4_3Layout.setVerticalGroup(
            tunel4_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(tunel4_3);
        tunel4_3.setBounds(70, 160, 50, 10);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema en ejecución...");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 1000, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean pausado = false;
    
    
    private void botonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausaActionPerformed
        // TODO add your handling code here:
        if (pausado) {
            ControlGlobal.reanudar();
            botonPausa.setText("Pausar");
        } else {
            ControlGlobal.pausar();
            botonPausa.setText("Reanudar");
        }
        pausado = !pausado;
    }//GEN-LAST:event_botonPausaActionPerformed

    private void btnVerHumanosZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHumanosZ3ActionPerformed
        // TODO add your handling code here:
        List<String> humanos = ZonaInsegura.get(3).getHumanosPresentes();

        StringBuilder sb = new StringBuilder("Humanos en Zona Insegura 3:\n");
        for (String h : humanos) {
            sb.append(" - ").append(h).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 3 - Humanos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerHumanosZ3ActionPerformed

    private void btnVerZombisZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZombisZ3ActionPerformed
        // TODO add your handling code here:
        List<String> zombis = ZonaInsegura.get(3).getZombisPresentes();

        StringBuilder sb = new StringBuilder("Zombis en Zona Insegura 3:\n");
        for (String z : zombis) {
            sb.append(" - ").append(z).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 3 - Zombis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerZombisZ3ActionPerformed

    private void btnVerHumanosZ0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHumanosZ0ActionPerformed
        // TODO add your handling code here:
        List<String> humanos = ZonaInsegura.get(0).getHumanosPresentes();

        StringBuilder sb = new StringBuilder("Humanos en Zona Insegura 0:\n");
        for (String h : humanos) {
            sb.append(" - ").append(h).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 0 - Humanos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerHumanosZ0ActionPerformed

    private void btnVerZombisZ0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZombisZ0ActionPerformed
        // TODO add your handling code here:
        List<String> zombis = ZonaInsegura.get(0).getZombisPresentes();

        StringBuilder sb = new StringBuilder("Zombis en Zona Insegura 0:\n");
        for (String z : zombis) {
            sb.append(" - ").append(z).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 0 - Zombis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerZombisZ0ActionPerformed

    private void btnVerHumanosZ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHumanosZ1ActionPerformed
        // TODO add your handling code here:
        List<String> humanos = ZonaInsegura.get(1).getHumanosPresentes();

        StringBuilder sb = new StringBuilder("Humanos en Zona Insegura 1:\n");
        for (String h : humanos) {
            sb.append(" - ").append(h).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 1 - Humanos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerHumanosZ1ActionPerformed

    private void btnVerZombisZ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZombisZ1ActionPerformed
        // TODO add your handling code here:
        List<String> zombis = ZonaInsegura.get(1).getZombisPresentes();

        StringBuilder sb = new StringBuilder("Zombis en Zona Insegura 1:\n");
        for (String z : zombis) {
            sb.append(" - ").append(z).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 1 - Zombis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerZombisZ1ActionPerformed

    private void btnVerHumanosZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHumanosZ2ActionPerformed
        // TODO add your handling code here:
        List<String> humanos = ZonaInsegura.get(2).getHumanosPresentes();

        StringBuilder sb = new StringBuilder("Humanos en Zona Insegura 2:\n");
        for (String h : humanos) {
            sb.append(" - ").append(h).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 2 - Humanos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerHumanosZ2ActionPerformed

    private void btnVerZombisZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZombisZ2ActionPerformed
        // TODO add your handling code here:
        List<String> zombis = ZonaInsegura.get(2).getZombisPresentes();

        StringBuilder sb = new StringBuilder("Zombis en Zona Insegura 2:\n");
        for (String z : zombis) {
            sb.append(" - ").append(z).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Zona Insegura 2 - Zombis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerZombisZ2ActionPerformed

    private void btnVerZonaComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZonaComunActionPerformed
        // TODO add your handling code here:
        List<String> humanos = refugio.getZonaComun().getHumanosPresentes();
        String lista = humanos.isEmpty() ? "No hay humanos actualmente." : String.join("\n", humanos);
        JOptionPane.showMessageDialog(this, lista, "Zona Común", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnVerZonaComunActionPerformed

    private void btnVerComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComedorActionPerformed
        // TODO add your handling code here:
        List<String> humanos = refugio.getComedor().getHumanosPresentes();
        String lista = humanos.isEmpty() ? "No hay humanos actualmente." : String.join("\n", humanos);
        JOptionPane.showMessageDialog(this, lista, "Comedor", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerComedorActionPerformed

    private void btnVerDescansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDescansoActionPerformed
        // TODO add your handling code here:
        List<String> humanos = refugio.getZonaDescanso().getHumanosPresentes();
        String lista = humanos.isEmpty() ? "No hay humanos actualmente." : String.join("\n", humanos);
        JOptionPane.showMessageDialog(this, lista, "Zona de Descanso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerDescansoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(refugio).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPausa;
    private javax.swing.JButton btnVerComedor;
    private javax.swing.JButton btnVerDescanso;
    private javax.swing.JButton btnVerHumanosZ0;
    private javax.swing.JButton btnVerHumanosZ1;
    private javax.swing.JButton btnVerHumanosZ2;
    private javax.swing.JButton btnVerHumanosZ3;
    private javax.swing.JButton btnVerZombisZ0;
    private javax.swing.JButton btnVerZombisZ1;
    private javax.swing.JButton btnVerZombisZ2;
    private javax.swing.JButton btnVerZombisZ3;
    private javax.swing.JButton btnVerZonaComun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblComidaDisponible;
    private javax.swing.JPanel tunel1;
    private javax.swing.JPanel tunel2;
    private javax.swing.JPanel tunel3_1;
    private javax.swing.JPanel tunel3_2;
    private javax.swing.JPanel tunel4_1;
    private javax.swing.JPanel tunel4_2;
    private javax.swing.JPanel tunel4_3;
    private javax.swing.JPanel zonaComedor;
    private javax.swing.JPanel zonaComun;
    private javax.swing.JPanel zonaDescanso;
    private javax.swing.JPanel zonaInsegura1;
    private javax.swing.JPanel zonaInsegura2;
    private javax.swing.JPanel zonaInsegura3;
    private javax.swing.JPanel zonaInsegura4;
    // End of variables declaration//GEN-END:variables
}
